version: '2'
services:
  web:
    build: .
    environment:
      - PORT=8080
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
      - "9005:9005" 
